### ISSUE TITLE
Issue when deploying artifact in remote Payara.

### ISSUE THREAD

**Issue by damien-biasotto** [payara/ecosystem-vscode-plugin#36]
Good Morning,

First of all thanks a lot for this extension, but I'm having trouble deploying a war file onto a remote payara (running in Docker).

The extension complains about the path not being found. (I remember having this issue a long time ago with IntelliJ (in the same context)

Does this plugin support remote payara?

I attached a picture to show that the war file exists, but the extension does not find it.

![remote-payara-issue](https://user-images.githubusercontent.com/430633/81626481-2d2d1080-943f-11ea-9ba7-6ade6de0f18d.png)

**Comment by jGauravGupta** [comment]
Hi @damien-biasotto,

Thanks for reporting the issue, Currently Payara Server remote instance not supported in VSCode.
I have created an internal ticket [ECOSYS-158](https://payara.atlassian.net/browse/ECOSYS-158) to address the issue.

**Comment by damien-biasotto** [comment]
Oh ok, thank you for the update.

Feel free to close the issue then :)
