### ISSUE TITLE
Payara Tools extension not working on VSCode on linux

### ISSUE THREAD

**Issue by alcarnes** [payara/ecosystem-vscode-plugin#45]
I am not able to run or debug a basic webapp in payara.  I can start the server but the "Run on Payara Server" and "Debug on Payara Server" options do not do anything.  I followed [this tutorial](https://blog.payara.fish/adding-payara-server-to-visual-studio-code)  My DevToolsConsole output is attached.
[DevToolsConsole.txt](https://github.com/payara/ecosystem-vscode-plugin/files/4767259/DevToolsConsole.txt)

I originally mentioned my issue in this [bug](https://github.com/payara/ecosystem-vscode-plugin/issues/30). However, that bug was closed.

**Comment by jGauravGupta** [comment]
Hi @alcarnes,

Can you please check out the latest released version [0.0.4](https://github.com/payara/ecosystem-vscode-plugin/releases/tag/0.0.4) and confirm the same.

**Comment by jGauravGupta** [comment]
Create an internal ticket FISH-613 to address it.
