### ISSUE TITLE
[Feature request] Redeploy the app in the context menu

### ISSUE THREAD

**Issue by yacut** [payara/ecosystem-vscode-plugin#60]
<img width="323" alt="Screenshot_2020-11-24_at_14_09_10" src="https://user-images.githubusercontent.com/4711633/100098705-b72e4b00-2e5e-11eb-8d55-7ac7617a9b87.png">

Also auto-redeploy will be great feature

**Comment by jGauravGupta** [comment]
Created internal ticket FISH-795 to address it.

**Comment by smillidge** [comment]
Fixed by #67
